[Service]
Environment=LD_PRELOAD=/home/tapcash/anaconda3/envs/ComfyUI/lib/libsqlite3.so.0
ExecStart=
ExecStart=/home/tapcash/ssd2/ComfyUI/.venv-music3/bin/python main.py --listen 0.0.0.0 --reserve-vram 8 --lowvram
